version: "3.8"

services:

  redis:
    image: 'bitnami/redis:latest'
    container_name: redisdb
    env_file:
      - .env

  db:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    env_file:
      - .env
    restart: always
    volumes:
      - .:/app/

    working_dir: "/app/product_api"
    container_name: api_container
    expose:
      - 80
    ports:
      - "80:80"
    command: python manage.py runserver 0.0.0.0:80 --insecure
    depends_on:
      - db
      - redis


volumes:
  mysql_data:
