version: "3.8"

services:
  redis:
    image: 'bitnami/redis:latest'
    container_name: redisdb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379

  db:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: productdb
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_ROOT_HOST: 'localhost'  # needs to be enclosed with quotes
    container_name: mysql-db
    ports:
      - 3306:3306

  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    env_file: 
      - .env
    restart: always
    volumes:
      - .:/app/
    depends_on:
      - db
      - redis
    working_dir: "/app/product_api"
    expose:
      - 8000
    ports:
      - "8000:8000"
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

volumes:
  mysql_data:
